#!/usr/bin/env bash

# failed 'tls: failed to verify certificate: x509: certificate relies on legacy Common Name field, use SANs instead'
# openssl genrsa -out bin/private.key 4096
# openssl req -new -x509 -sha256 -days 1825 -key bin/private.key -out bin/public.crt

# https://go-review.googlesource.com/c/go/+/231379
# https://github.com/virtualmin/virtualmin-gpl/issues/462#issuecomment-1267895524

CA_KEY=bin/ca.key
CA_CRT=bin/ca.crt
SERVER_KEY=bin/server.key
SERVER_CSR=bin/server.csr
SERVER_CRT=bin/server.crt

# create CA cert
openssl genrsa -out $CA_KEY 2048
openssl req -new -x509 -days 365 -key $CA_KEY -subj "/C=CN/ST=SC/L=CD/O=Anddd7/CN=Anddd7 Root CA" -out $CA_CRT
# create CSR
openssl req -newkey rsa:2048 -nodes -keyout $SERVER_KEY -subj "/C=CN/ST=SC/L=CD/O=Anddd7/CN=localhost" -out $SERVER_CSR
# create server cert
openssl x509 -req -extfile <(printf "subjectAltName=DNS:localhost") -days 365 -in $SERVER_CSR -CA $CA_CRT -CAkey $CA_KEY -CAcreateserial -out $SERVER_CRT